
services:
  nginx: 
    image: nginx:stable-alpine
    ports:
      - "8000:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./laravel-kinodvizh:/app
    depends_on:
      - laravel-kinodvizh

  laravel-kinodvizh:
    container_name: laravel-kinodvizh
    build:
      context: .
      dockerfile: ./dockerfiles/laravel-kinodvizh/Dockerfile
    expose:
      - "9000"
    volumes:
      - ./laravel-kinodvizh:/app
    depends_on:
      - mysql

  react-kinodvizh:
    container_name: react-kinodvizh
    build:
      context: .
      dockerfile: ./dockerfiles/react-kinodvizh/Dockerfile
    volumes:
      - /app/node_modules
    ports:
      - "5173:5173"
    depends_on:
      - laravel-kinodvizh

  mysql:
    image: mysql:8.0
    ports:
      - "3316:3306"
    environment:
      - MYSQL_DATABASE=kinodvizh
      - MYSQL_ROOT_PASSWORD=secret
    volumes:
      - ./mysql_data:/var/lib/mysql

volumes:
  mysql_data:
